BookCard Component
zemoga/ui-test-skill-up pull request #2
Opened 2022-07-07 19:44 UTC by lesliefernandez10

2022-07-07 21:01 UTC, josezumaque requested changes

2022-07-08 13:58 UTC, lesliefernandez10 commented on src/components/BookCard.vue
> +  display: grid;
Done, thanks!

2022-07-08 14:27 UTC, josezumaque requested changes

2022-07-08 14:27 UTC, josezumaque commented on src/components/BookCard.vue
>  .line-clamp {
Since this is a utility class, should be moved into a global css file.

2022-07-08 15:23 UTC, lesliefernandez10 commented on src/components/BookCard.vue
>  .line-clamp {
Done!

2022-07-08 16:37 UTC, josezumaque approved these changes
Good job!

2022-07-08 16:57 UTC, merged

2022-07-11 14:29 UTC, josezumaque reviewed
Good job!