Fix/zmb 100 - Add the homepage desktop view
zemoga/ui-test-skill-up pull request #21
Opened 2022-07-27 17:08 UTC by lesliefernandez10

This PR also does the following:

- When there are no proposed or active books, a message will appear informing the user.
- Changes the prop name of the back button inside the main header component to make it more descriptive.

2022-07-27 17:51 UTC, mariacuadroszm requested changes

2022-07-27 17:51 UTC, mariacuadroszm commented on src/components/BookCard.vue
> +    padding-inline: 1.8rem;
You could use px-6 class

2022-07-27 17:51 UTC, mariacuadroszm commented on src/components/BooksList.vue
> +  <div class="carousel my-5" v-if="noBooks">
You should change the name of the variable noBooks (maybe for availableBooks or something that means that there are books to display), is a little confusing because when the variable is true (the are no books) then you display all the books. When you read it, it does the contrary of how the variable is named.

2022-07-27 17:51 UTC, mariacuadroszm commented on src/components/BooksList.vue
>  @media (min-width: 1024px) {
Why did you add this extra media queries?

2022-07-27 18:16 UTC, lesliefernandez10 commented on src/components/BooksList.vue
> +  <div class="carousel my-5" v-if="noBooks">
Done

2022-07-27 18:19 UTC, lesliefernandez10 commented on src/components/BooksList.vue
>  @media (min-width: 1024px) {
Because the button changes size after 768px so it's no longer centered to the screen

2022-07-27 18:20 UTC, lesliefernandez10 commented on src/components/BookCard.vue
> +    padding-inline: 1.8rem;
I could add it as a reactive class, let me test it out

2022-07-27 19:17 UTC, mariacuadroszm approved these changes

2022-07-28 15:13 UTC, josezumaque requested changes

2022-07-28 15:13 UTC, josezumaque commented on src/views/HomeView.vue
> +      noActiveBooks: true,
You don't need a prop to control this behavior. This should be a computed property inside BookList component.
If `books` is `undefined` or is an empty array you can assume that there're no books.

2022-07-28 17:17 UTC, lesliefernandez10 commented on src/views/HomeView.vue
> +      noActiveBooks: true,
done

2022-07-28 19:56 UTC, josezumaque requested changes

2022-07-28 19:56 UTC, josezumaque commented on src/components/BooksList.vue
> +      return this.books === undefined || this.books <= 0 ? "no-books" : "";
The right way should be `return !this.books || !this.books.length`

2022-07-28 19:56 UTC, josezumaque commented on src/components/BooksList.vue
> +      return this.books === undefined || this.books <= 0 ? "center" : "";
This is the same as above one, so you can use just one and rename it if needed.

2022-07-28 20:07 UTC, lesliefernandez10 commented on src/components/BooksList.vue
> +      return this.books === undefined || this.books <= 0 ? "center" : "";
The conditional is the same but the classes that are being applied are different, could you please clarify?

2022-07-28 21:32 UTC, lesliefernandez10 commented on src/components/BooksList.vue
> +      return this.books === undefined || this.books <= 0 ? "no-books" : "";
I think it should be done now

2022-07-28 21:32 UTC, lesliefernandez10 commented on src/components/BooksList.vue
> +      return this.books === undefined || this.books <= 0 ? "center" : "";
I think it should be done now

2022-07-28 22:19 UTC, josezumaque approved these changes

2022-07-28 22:33 UTC, merged